apiVersion: apps/v1
kind: Deployment
metadata: 
  name: productsapp-k8
spec:
replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
    app: productsapp-k8
  template:
    metadata:
    labels:
      app: productapp-k8
    spec:
      containers:
      -name: myapp
      image: kpradeep/devops-groovy-products
      resources:
        limits:
         memory: "128Mi"
          cpu: "500m"
      ports:
      -containerPort: 9080

